version: '3.8'
services:
  dev-db:
    container_name: nestjs-api-tutorial-dev-db-1
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp
  test-db:
    container_name: nestjs-api-tutorial-test-db-1
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    networks:
      - freecodecamp
networks:
  freecodecamp:
